site_name: MDEF Docs
site_description: Master on Design For Emergent Futures Documentation
site_author: IAAC, ELISAVA, Fab Lab Barcelona
site_url: https://emergentfutures.fablabbcn.org
repo_name: mdef-docs
repo_url: https://github.com/fablabbcn/mdef-docs

nav:
  - Main: index.md
  - Academic Year 2022-23:
    - Main: academic_year_2022_23/index.md
    - Calendar: academic_year_2022_23/calendar_2022_23/index.md
    - Students Websites: academic_year_2022_23/students_websites_2022_23/index.md
    - Term 1:
      - academic_year_2022_23/term_1_2022_23/index.md
      - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
      - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
      - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
      - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
      - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
      - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
      - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
      - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md

    - Previous Years:
      - Main: previous_years/index.md
      - Academic Year 2021-22:
        - Main: academic_year_2022_23/index.md
        - Students Websites: academic_year_2022_23/students_websites_2022_23/index.md
        - Student Awards:
        -  Research Trip:
        - Term 1:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
        - Term 2:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
        - Term 3:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md

      - Academic Year 2020-21:
        - Main: academic_year_2022_23/index.md
        - Students Websites: academic_year_2022_23/students_websites_2022_23/index.md
        - Student Awards:
        -  Research Trip:
        - Term 1:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
        - Term 2:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
        - Term 3:
          - academic_year_2022_23/term_1_2022_23/index.md
          - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
          - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
          - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
          - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
          - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
          - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
          - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
          - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md

      - Academic Year 2019-20:
          - Main: academic_year_2022_23/index.md
          - Students Websites: academic_year_2022_23/students_websites_2022_23/index.md
          - Student Awards:
          -  Research Trip:
          - Term 1:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
          - Term 2:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
          - Term 3:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md

      - Academic Year 2018-19:
          - Main: academic_year_2022_23/index.md
          - Students Websites: academic_year_2022_23/students_websites_2022_23/index.md
          - Student Awards:
          -  Research Trip:
          - Term 1:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
          - Term 2:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md
          - Term 3:
            - academic_year_2022_23/term_1_2022_23/index.md
            - Design Studio Term 1: academic_year_2022_23/term_1_2022_23/design_studio_framing_design_interventions_2022_23/index.md
            - Bootcamp: academic_year_2022_23/term_1_2022_23/mdef_bootcamp_2022_23/index.md
            - Atles of Weak Signals: academic_year_2022_23/term_1_2022_23/atlas_of_weak_signals_2022_23_(aows)/index.md
            - Biology & Agri 0: academic_year_2022_23/term_1_2022_23/biology_&_agri_zero_2022_23/index.md
            - Living With Your Own Ideas: academic_year_2022_23/term_1_2022_23/living_with_your_own_ideas_2022_23/index.md
            - Tech Beyond The Myth: academic_year_2022_23/term_1_2022_23/tech_beyond_the_myth_2022_23/index.md
            - Community Engagement: academic_year_2022_23/term_1_2022_23/community_engagement_2022_23/index.md
            - Extended Intelligences: academic_year_2022_23/term_1_2022_23/extended_intelligences_2022_23/index.md


<<<<<<< HEAD

=======
  - Meta: meta/index.md
>>>>>>> e9f6d272663c247b476a9b8750038e5033a93de5

#    - Term 2: 2022/term2_2022_23.md
#    - Term 3: 2022/term3_2022_23.md
#  - Previous Years:
#    - Main: 2022/index.md
#    - Academic Year 2021-22:
#      - Main: 2022/index.md
#      - Calendar: 2022/calendar_2022_23.md
#      - Term 1: 2022/term1_2022_23.md
#      - Term 2: 2022/term2_2022_23.md
#      - Term 3: 2022/term3_2022_23.md
#    - Academic Year 2020-21:
#      - Main: 2022/index.md
#      - Calendar: 2022/calendar_2022_23.md
#      - Term 1: 2022/term1_2022_23.md
#      - Term 2: 2022/term2_2022_23.md
#      - Term 3: 2022/term3_2022_23.md
#    - Academic Year 2019-20:
#      - Main: 2022/index.md
#      - Calendar: 2022/calendar_2022_23.md
#      - Term 1: 2022/term1_2022_23.md
#      - Term 2: 2022/term2_2022_23.md
#      - Term 3: 2022/term3_2022_23.md
#    - Academic Year 2018-19:
#      - Main: 2022/index.md
#      - Calendar: 2022/calendar_2022_23.md
#      - Term 1: 2022/term1_2022_23.md
#      - Term 2: 2022/term2_2022_23.md
#      - Term 3: 2022/term3_2022_23.md




theme:
  language: 'en'
  name: 'material'
  features:
    - instant
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.tooltips
  custom_dir: 'custom_theme'
  palette:
    # See assets/stylesheets/extra.css file for the color definitions
    # Palette toggle for light mode
    - scheme: mdef
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # Logo is not yet available
  # logo: 'assets/images/logo.svg'
  # favicon: 'assets/images/favicon.ico'
  icon:
    repo: fontawesome/brands/git-alt

extra_css:
  - assets/stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/fablabbcn'
    - icon: fontawesome/brands/instagram
      link: 'https://www.instagram.com/fablabbcn/'
    - icon: fontawesome/brands/github
      link: 'https://www.github.com/fablabbcn/'
  # project: ''
  # footer_logo: '/assets/images/eu-flag.png'
  fullscreen_button: true

plugins:
  - macros
  - search

markdown_extensions:
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
  - 'assets/javascripts/extra.js'
  - 'assets/javascripts/google-drive.js'
